kind: pipeline
name: update-github-pages

clone:
  disable: true

steps:
  - name: clone
    image: docker:git
    commands:
      - git clone --depth 1 https://github.com/sfosc/sourcecred.git .
      - git submodule init
      - git submodule update

  - name: restore-cache
    image: meltwater/drone-cache:1
    settings:
      restore: true
      cache_key: '{{ .Repo.Namespace }}-{{ .Repo.Name }}/cron-cache'
      backend: filesystem
      archive_format: gzip
      mount:
        - './sourcecred_data/cache'
        - './sourcecred/node_modules'
        - './widgets/node_modules'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: build
    image: node:10
    environment:
      SOURCECRED_GITHUB_TOKEN:
        from_secret: SOURCECRED_GITHUB_TOKEN
      SSH_BOT_KEY:
        from_secret: SSH_BOT_KEY
    commands:
      # Use a bot key for reading.
      - mkdir -p ~/.ssh
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - echo "$SSH_BOT_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      - ./scripts/rebuild-site.sh

  - name: rebuild-cache
    image: meltwater/drone-cache:1
    settings:
      rebuild: true
      cache_key: '{{ .Repo.Namespace }}-{{ .Repo.Name }}/cron-cache'
      backend: filesystem
      archive_format: gzip
      mount:
        - './sourcecred_data/cache'
        - './sourcecred/node_modules'
        - './widgets/node_modules'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: commit-and-push
    image: docker:git
    environment:
      SSH_DEPLOY_KEY:
        from_secret: SSH_DEPLOY_KEY
    commands:
      # Switch to the secret deploy key.
      - mkdir -p ~/.ssh
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      - cd site
      - git init
      - git config user.email "bot@sfosc.org"
      - git config user.name "Deployment Bot"
      - git checkout -b gh-pages
      - git add --all
      - git commit -m "Publishing to gh-pages `date`"
      - git push -f git@github.com:sfosc/sourcecred.git gh-pages

trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /var/cache/drone
