kind: pipeline
name: update-github-pages

clone:
  disable: true

steps:
  - name: clone
    image: docker:git
    commands:
      - git clone --depth 1 https://github.com/sfosc/sourcecred.git .
      - git submodule init
      - git submodule update

  - name: restore-cache
    image: meltwater/drone-cache:1
    environment: &minio-cache-env
      S3_ENDPOINT: https://minio.sfosc.robin-it.com
      S3_REGION: eu-west-1
      S3_BUCKET: drone-cache-sfosc
      # Path style buckets is used for minio hosts, AWS S3 should be false
      PLUGIN_PATH_STYLE: true
      PLUGIN_ARCHIVE_FORMAT: gzip
      PLUGIN_ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY
      PLUGIN_SECRET_KEY:
        from_secret: MINIO_SECRET_KEY
    settings:
      restore: true
      cache_key: update-github-pages
      mount:
        - './sourcecred_data/cache'
        - './sourcecred/node_modules'
        - './widgets/node_modules'

  # - name: build
  #   image: node:10
  #   environment:
  #     SOURCECRED_GITHUB_TOKEN:
  #       from_secret: SOURCECRED_GITHUB_TOKEN
  #     SSH_BOT_KEY:
  #       from_secret: SSH_BOT_KEY
  #   commands:
  #     # Use a bot key for reading.
  #     - mkdir -p ~/.ssh
  #     - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  #     - echo "$SSH_BOT_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
  #     - ./scripts/rebuild-site.sh

  - name: build-dummy
    image: node:10
    commands:
      - mkdir -p sourcecred_data/cache sourcecred/node_modules widgets/node_modules
      - ls -l sourcecred_data/cache
      - ls -l sourcecred/node_modules
      - ls -l widgets/node_modules
      - touch sourcecred_data/cache/testing-cache
      - touch sourcecred/node_modules/testing-cache
      - touch widgets/node_modules/testing-cache

  - name: rebuild-cache-sourcecred
    image: meltwater/drone-cache:1
    environment: *minio-cache-env
    settings:
      rebuild: true
      cache_key: update-github-pages
      mount:
        - './sourcecred_data/cache'

  - name: rebuild-cache-node-modules
    image: meltwater/drone-cache:1
    environment: *minio-cache-env
    settings:
      rebuild: true
      cache_key: update-github-pages
      mount:
        - './sourcecred/node_modules'
        - './widgets/node_modules'

  # - name: commit-and-push
  #   image: docker:git
  #   environment:
  #     SSH_DEPLOY_KEY:
  #       from_secret: SSH_DEPLOY_KEY
  #   commands:
  #     # Switch to the secret deploy key.
  #     - mkdir -p ~/.ssh
  #     - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  #     - echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
  #     - cd site
  #     - git init
  #     - git config user.email "bot@sfosc.org"
  #     - git config user.name "Deployment Bot"
  #     - git checkout -b gh-pages
  #     - git add --all
  #     - git commit -m "Publishing to gh-pages `date`"
      # - git push -f git@github.com:sfosc/sourcecred.git gh-pages

# trigger:
#   branch:
#     - master
